### ISSUE TITLE
Nuvlabox security container is using 343MB of RAM

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvlabox/security#5]
try release memory via nmap, or ultimately partition the nmap execution per file slices to load less in memory at a time.

Also put limits on container

**Comment by cjdcordeiro** [comment]
@0xbase12 I couldn't reproduce the memory issue but I couldn't. It is true that nmap consumes a lot of memory while running, but this memory is released after the process finishes.

I've added `--release-memory` to the command anyway.

Adding container limits doesn't help as the container gets killed with a kernel panic.

**Comment by mebster** [comment]
One thing to try is to delay the execution of nmap on startup.  Having a process take all the cpu at start-up is not a good idea.  And it delays other component to kick in.

**Comment by cjdcordeiro** [comment]
sure, put a ticket for it pls

**Comment by 0xbase12** [comment]
The security container run following command: 
```nmap_scan_cmd = ['sh', '-c', 'nmap -sV --script vulscan/ --script-args vulscandb=%s,vulscanoutput=nuvlabox-cve,vulscanshowall=1 localhost --exclude-ports 5080 -oX %s --release-memory' [vulscan_db, vulscan_out_file]```

Where the vulscan_db is a csv file of ~150MB. This file is going to grow each year of some MBs. Could we partition this file by 20MB and run the nmap command in a loop with each partition of the db to reduce the memory footprint of that container?

**Comment by cjdcordeiro** [comment]
we could try to do that. the problem is how to build the final XML file that will be sent to the `agent`. we would need to send multiple XML files I think...and then have the agent parse them one by one, aggregate the final results and send that to Nuvla. 

It can possibly be done though. Pls put a ticket for it

**Comment by 0xbase12** [comment]
The security container aggregate the result in one xml that he send to the agent.
